import type { AnnouncementEntry, BehaviourLogEntry, Child } from '@/types';

export interface HomeworkItem {
  title: string;
  subject: string;
  type: string;
  dueDate: string;
  color: string;
  status: string;
  statusVariant: "emerald" | "amber" | "red" | "blue" | "slate";
}

export const PARENT_NAME = 'Bekele';

export const CHILDREN: Child[] = [
  {
    id: "STU-00421",
    branchId: "branch-1",
    branchName: "Main Branch",
    sectionId: "section-1",
    name: "Sara Bekele",
    initials: "SB",
    grade: "7",
    section: "A",
    overallAvg: 76,
    attendance: 97,
    assignmentsDue: 2,
    missingWork: 1,
    subjects: [
      {
        name: "Mathematics",
        score: 78,
        color: "#3949ab",
        teacher: "Mr. Tesfaye",
      },
      { name: "Physics", score: 74, color: "#7c3aed", teacher: "Ms. Bekele" },
      { name: "Biology", score: 76, color: "#059669", teacher: "Ms. Haile" },
    ],
    attendance_log: [
      { date: "2025-06-02", status: "present" },
      { date: "2025-06-03", status: "present" },
      { date: "2025-06-04", status: "present" },
      { date: "2025-06-05", status: "present" },
      { date: "2025-06-06", status: "present" },
      { date: "2025-05-26", status: "present" },
      { date: "2025-05-27", status: "absent" },
      { date: "2025-05-28", status: "present" },
      { date: "2025-05-29", status: "late" },
      { date: "2025-05-30", status: "present" },
    ],
    homework: [
      {
        id: "HW-1",
        title: "Linear Equations Practice",
        subject: "Mathematics",
        subjectColor: "#3949ab",
        date: "Jun 2",
        score: 7,
        maxScore: 10,
        status: "graded",
        type: "Homework",
      },
      {
        id: "HW-2",
        title: "Newton's Laws Questions",
        subject: "Physics",
        subjectColor: "#7c3aed",
        date: "Jun 1",
        score: null,
        maxScore: 10,
        status: "missing",
        type: "Homework",
      },
    ],
    assignments: [
      {
        id: "ASN-1",
        title: "Chapter 3 Summary — Algebra",
        subject: "Mathematics",
        subjectColor: "#3949ab",
        type: "Homework",
        dueDate: "Jun 3, 2025",
        status: "due",
        score: null,
        maxScore: 20,
        description: "Write a one-page summary of Chapter 3.",
      },
      {
        id: "ASN-2",
        title: "Mid-Term Practice Quiz",
        subject: "Mathematics",
        subjectColor: "#3949ab",
        type: "Quiz",
        dueDate: "Jun 2, 2025",
        status: "graded",
        score: 22,
        maxScore: 30,
        description: "20-question practice quiz for the mid-term.",
      },
      {
        id: "ASN-3",
        title: "Newton's Laws Lab Report",
        subject: "Physics",
        subjectColor: "#7c3aed",
        type: "Lab Report",
        dueDate: "Jun 5, 2025",
        status: "due",
        score: null,
        maxScore: 50,
        description: "Submit the lab report from last Thursday.",
      },
    ],
    messages: [
      {
        id: "M1",
        teacherName: "Mr. Tesfaye",
        teacherInitials: "MT",
        subject: "Mathematics",
        preview: "Sara is working hard this term in Mathematics classes.",
        time: "9:42 AM",
        unread: true,
      },
    ],
    notifications: [
      {
        id: "N1",
        type: "grade",
        title: "Grade posted — Algebra Practice",
        category: "grade",
        time: "Just now",
        read: false,
        detail: "Mathematics · 7/10 · Just now",
      },
      {
        id: "N2",
        type: "urgent",
        title: "Assignment due in 2 days",
        category: "announcement",
        time: "Jun 3",
        read: false,
        detail: "Chapter 3 Summary · Jun 3",
      },
    ],
    schedule: [
      {
        id: "S1",
        time: "7:30 AM",
        subject: "Mathematics",
        teacher: "Mr. Tesfaye",
        room: "Room 12",
        color: "#3949ab",
        type: "Lecture",
      },
      {
        id: "S2",
        time: "9:00 AM",
        subject: "Physics",
        teacher: "Ms. Bekele",
        room: "Room 7",
        color: "#7c3aed",
        type: "Lab",
      },
      {
        id: "S3",
        time: "10:30 AM",
        subject: "Biology",
        teacher: "Ms. Haile",
        room: "Room 9",
        color: "#059669",
        type: "Lecture",
      },
    ],
  },
  {
    id: "STU-00398",
    branchId: "branch-1",
    branchName: "Main Branch",
    sectionId: "section-2",
    name: "Yonas Bekele",
    initials: "YB",
    grade: "4",
    section: "B",
    overallAvg: 84,
    attendance: 94,
    assignmentsDue: 0,
    missingWork: 0,
    subjects: [
      { name: "English", score: 85, color: "#0891b2", teacher: "Mr. Alemu" },
      {
        name: "Mathematics",
        score: 83,
        color: "#3949ab",
        teacher: "Mr. Tesfaye",
      },
      { name: "Science", score: 84, color: "#059669", teacher: "Ms. Haile" },
    ],
    attendance_log: [
      { date: "2025-06-02", status: "present" },
      { date: "2025-06-03", status: "present" },
      { date: "2025-06-04", status: "present" },
      { date: "2025-06-05", status: "present" },
      { date: "2025-06-06", status: "present" },
    ],
    homework: [
      {
        id: "HW-B1",
        title: "Reading comprehension",
        subject: "English",
        subjectColor: "#0891b2",
        date: "Jun 2",
        score: 8,
        maxScore: 10,
        status: "graded",
        type: "Homework",
      },
      {
        id: "HW-B2",
        title: "Algebra Patterns",
        subject: "Mathematics",
        subjectColor: "#3949ab",
        date: "Jun 1",
        score: 9,
        maxScore: 10,
        status: "graded",
        type: "Homework",
      },
    ],
    assignments: [
      {
        id: "ASN-B1",
        title: "Science Water Cycle Diagram",
        subject: "Science",
        subjectColor: "#059669",
        type: "Project",
        dueDate: "Jun 4, 2025",
        status: "submitted",
        score: null,
        maxScore: 20,
        description: "Draw and label the steps of the water cycle.",
      },
    ],
    messages: [],
    notifications: [
      {
        id: "N-B1",
        type: "grade",
        title: "Science diagram submitted",
        category: "grade",
        time: "Awaiting review",
        read: false,
        detail: "Awaiting review by Ms. Haile",
      },
    ],
    schedule: [
      {
        id: "SB1",
        time: "7:30 AM",
        subject: "Mathematics",
        teacher: "Mr. Tesfaye",
        room: "Room 8",
        color: "#3949ab",
        type: "Lecture",
      },
      {
        id: "SB2",
        time: "9:00 AM",
        subject: "English",
        teacher: "Mr. Alemu",
        room: "Room 2",
        color: "#0891b2",
        type: "Lecture",
      },
      {
        id: "SB3",
        time: "10:30 AM",
        subject: "Science",
        teacher: "Ms. Haile",
        room: "Room 9",
        color: "#059669",
        type: "Lab",
      },
    ],
  },
  {
    id: "STU-00502",
    branchId: "branch-1",
    branchName: "Main Branch",
    sectionId: "section-3",
    name: "Liya Bekele",
    initials: "LB",
    grade: "10",
    section: "A",
    overallAvg: 89,
    attendance: 95,
    assignmentsDue: 3,
    missingWork: 0,
    subjects: [
      { name: "Chemistry", score: 87, color: "#0891b2", teacher: "Ms. Almaz" },
      { name: "History", score: 92, color: "#d97706", teacher: "Mr. Girma" },
      {
        name: "English Lit",
        score: 88,
        color: "#7c3aed",
        teacher: "Ms. Kidist",
      },
    ],
    attendance_log: [
      { date: "2025-06-02", status: "present" },
      { date: "2025-06-03", status: "present" },
      { date: "2025-06-04", status: "present" },
      { date: "2025-06-05", status: "present" },
      { date: "2025-06-06", status: "present" },
    ],
    homework: [
      {
        id: "HW-C1",
        title: "Stoichiometry Worksheet",
        subject: "Chemistry",
        subjectColor: "#0891b2",
        date: "Jun 2",
        score: 9,
        maxScore: 10,
        status: "graded",
        type: "Homework",
      },
      {
        id: "HW-C2",
        title: "French Revolution Quiz",
        subject: "History",
        subjectColor: "#d97706",
        date: "Jun 1",
        score: 10,
        maxScore: 10,
        status: "graded",
        type: "Homework",
      },
    ],
    assignments: [
      {
        id: "ASN-C1",
        title: "Lab Report: Gas Laws",
        subject: "Chemistry",
        subjectColor: "#0891b2",
        type: "Lab Report",
        dueDate: "Jun 6, 2025",
        status: "due",
        score: null,
        maxScore: 50,
        description: "Submit detailed research on ideal gas laws in lab conditions.",
      },
      {
        id: "ASN-C2",
        title: "Hamlet Essay Draft",
        subject: "English Lit",
        subjectColor: "#7c3aed",
        type: "Essay",
        dueDate: "Jun 5, 2025",
        status: "due",
        score: null,
        maxScore: 30,
        description: "Draft analysis of Hamlet's third soliloquy.",
      },
      {
        id: "ASN-C3",
        title: "WWI Timeline Project",
        subject: "History",
        subjectColor: "#d97706",
        type: "Project",
        dueDate: "Jun 7, 2025",
        status: "due",
        score: null,
        maxScore: 40,
        description: "Create visual timeline of events leading up to first world war.",
      },
    ],
    messages: [
      {
        id: "MC1",
        teacherName: "Ms. Almaz",
        teacherInitials: "MA",
        subject: "Chemistry",
        preview: "Liya is taking exceptionally mature leadership in laboratory practices. Superb work.",
        time: "Just now",
        unread: true,
      },
    ],
    notifications: [
      {
        id: "NC1",
        type: "grade",
        title: "New Lab Report assigned",
        category: "announcement",
        time: "Due Jun 6",
        read: false,
        detail: "Due Jun 6 · Gas Laws",
      },
    ],
    schedule: [
      {
        id: "SC1",
        time: "7:30 AM",
        subject: "Chemistry",
        teacher: "Ms. Almaz",
        room: "Room 14",
        color: "#0891b2",
        type: "Lab",
      },
      {
        id: "SC2",
        time: "9:00 AM",
        subject: "History",
        teacher: "Mr. Girma",
        room: "Room 5",
        color: "#d97706",
        type: "Lecture",
      },
      {
        id: "SC3",
        time: "10:30 AM",
        subject: "English Lit",
        teacher: "Ms. Kidist",
        room: "Room 11",
        color: "#7c3aed",
        type: "Lecture",
      },
    ],
  },
];

export const HOMEWORK_MAP: Record<string, HomeworkItem[]> = {
  "STU-00421": [
    {
      title: "Solve Quadratic Equations",
      subject: "Mathematics",
      type: "10 questions",
      dueDate: "Due tomorrow",
      color: "#3949ab",
      status: "in progress",
      statusVariant: "amber",
    },
    {
      title: "Gravity & Friction Worksheet",
      subject: "Physics",
      type: "Problem solving",
      dueDate: "Due in 2 days",
      color: "#7c3aed",
      status: "not started",
      statusVariant: "slate",
    },
    {
      title: "Draw Plant Cell Diagram & label organelles",
      subject: "Biology",
      type: "Diagram drawing",
      dueDate: "Due Friday",
      color: "#059669",
      status: "due tomorrow",
      statusVariant: "red",
    },
  ],
  "STU-00398": [
    {
      title: "Adverbs and Adjectives Practice",
      subject: "English",
      type: "Grammar exercise",
      dueDate: "Due tomorrow",
      color: "#0891b2",
      status: "in progress",
      statusVariant: "amber",
    },
    {
      title: "Division Word Problems",
      subject: "Mathematics",
      type: "12 questions",
      dueDate: "Due in 2 days",
      color: "#3949ab",
      status: "not started",
      statusVariant: "slate",
    },
    {
      title: "Water Cycle Stages Poster",
      subject: "Science",
      type: "Drawing + labels",
      dueDate: "Due Friday",
      color: "#059669",
      status: "due tomorrow",
      statusVariant: "red",
    },
  ],
  "STU-00502": [
    {
      title: "Balancing Chemical Equations",
      subject: "Chemistry",
      type: "15 questions",
      dueDate: "Due tomorrow",
      color: "#0891b2",
      status: "in progress",
      statusVariant: "amber",
    },
    {
      title: "French Revolution Timeline",
      subject: "History",
      type: "Reading + summary",
      dueDate: "Due in 2 days",
      color: "#d97706",
      status: "not started",
      statusVariant: "slate",
    },
    {
      title: "Analytical Essay Outline",
      subject: "English Lit",
      type: "Outline draft",
      dueDate: "Due Friday",
      color: "#7c3aed",
      status: "due tomorrow",
      statusVariant: "red",
    },
  ],
};

export const BEHAVIOUR_LOG_BY_CHILD_ID: Record<string, BehaviourLogEntry[]> = {
  "STU-00421": [
    {
      id: "beh-1",
      childId: "STU-00421",
      type: "remark",
      title: "Teacher Remark",
      detail: "Shows strong analytical reading skills and supports classmates during group work.",
      teacherName: "Sarah J.",
      subject: "English",
      severity: "remark",
      recordedAt: "2026-05-15T09:30:00Z",
    },
    {
      id: "beh-2",
      childId: "STU-00421",
      type: "incident",
      title: "Late Assignment Submission",
      detail: "Mathematics homework was submitted after the class deadline.",
      teacherName: "Abebe T.",
      subject: "Mathematics",
      severity: "warning",
      recordedAt: "2026-05-12T08:00:00Z",
    },
    {
      id: "beh-3",
      childId: "STU-00421",
      type: "incident",
      title: "Disruptive Classroom Behaviour",
      detail: "Repeated side conversations interrupted the lesson and required intervention.",
      teacherName: "Tsige K.",
      subject: "Physics",
      severity: "serious",
      recordedAt: "2026-05-08T11:00:00Z",
    },
    {
      id: "beh-4",
      childId: "STU-00421",
      type: "remark",
      title: "Teacher Remark",
      detail: "Highly capable student, but needs better focus during independent practice.",
      teacherName: "Abebe Tadese",
      subject: "Mathematics",
      severity: "remark",
      recordedAt: "2026-05-06T14:15:00Z",
    },
  ],
  "STU-00398": [
    {
      id: "beh-5",
      childId: "STU-00398",
      type: "remark",
      title: "Teacher Remark",
      detail: "Consistently participates and arrives prepared for morning reading.",
      teacherName: "Rahel M.",
      subject: "English",
      severity: "remark",
      recordedAt: "2026-05-18T07:45:00Z",
    },
    {
      id: "beh-6",
      childId: "STU-00398",
      type: "incident",
      title: "Excellent Conduct",
      detail: "Helped organize classroom materials and modelled respectful behavior.",
      teacherName: "Martha B.",
      subject: "Homeroom",
      severity: "good",
      recordedAt: "2026-05-11T10:30:00Z",
    },
  ],
  "STU-00502": [
    {
      id: "beh-7",
      childId: "STU-00502",
      type: "incident",
      title: "Incomplete Homework",
      detail: "Chemistry worksheet was turned in without the final problem set.",
      teacherName: "Kebede M.",
      subject: "Chemistry",
      severity: "warning",
      recordedAt: "2026-05-09T13:00:00Z",
    },
  ],
};

export const ANNOUNCEMENTS_MOCK: AnnouncementEntry[] = [
  {
    id: "ann-1",
    branchId: "branch-1",
    organizationId: "org-1",
    subject: "Grade 7 Parent Briefing",
    message: "Parents of Grade 7 students are invited to a briefing on academic support plans.",
    isUrgent: false,
    status: "SENT",
    targetRoles: "PARENTS",
    targetGrades: ["grade-7"],
    targetSections: [],
    scheduledAt: null,
    createdAt: "2026-05-29T09:00:00Z",
    updatedAt: "2026-05-29T09:30:00Z",
    effectiveAt: "2026-05-29T09:30:00Z",
  },
  {
    id: "ann-2",
    branchId: "branch-1",
    organizationId: "org-1",
    subject: "Whole-Branch Safety Reminder",
    message: "All parents should review the revised student pick-up timing for this month.",
    isUrgent: true,
    status: "SENT",
    targetRoles: "PARENTS",
    targetGrades: [],
    targetSections: [],
    scheduledAt: null,
    createdAt: "2026-05-27T08:00:00Z",
    updatedAt: "2026-05-27T08:00:00Z",
    effectiveAt: "2026-05-27T08:00:00Z",
  },
  {
    id: "ann-3",
    branchId: "branch-1",
    organizationId: "org-1",
    subject: "Section A Materials Check",
    message: "Grade 7 Section A families should send geometry sets by Friday, June 6, 2026.",
    isUrgent: false,
    status: "SCHEDULED",
    targetRoles: "PARENTS",
    targetGrades: [],
    targetSections: ["section-1"],
    scheduledAt: "2026-06-05T06:00:00Z",
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-06-01T10:00:00Z",
    effectiveAt: "2026-06-05T06:00:00Z",
  },
  {
    id: "ann-4",
    branchId: "branch-1",
    organizationId: "org-1",
    subject: "Grade 4 Reading Day",
    message: "Grade 4 parents are invited to attend the reading day showcase next Wednesday.",
    isUrgent: false,
    status: "SENT",
    targetRoles: "PARENTS",
    targetGrades: ["grade-4"],
    targetSections: [],
    scheduledAt: null,
    createdAt: "2026-05-26T09:00:00Z",
    updatedAt: "2026-05-26T09:00:00Z",
    effectiveAt: "2026-05-26T09:00:00Z",
  },
];
